// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Qfm0kEEILIuqvgu21OnlhSkWoBiyVNQ',
    appId: '1:795859017189:web:0204c3b924e87c1e53230c',
    messagingSenderId: '795859017189',
    projectId: 'travelapp-428516',
    authDomain: 'travelapp-428516.firebaseapp.com',
    storageBucket: 'travelapp-428516.appspot.com',
    measurementId: 'G-ZGXS9B7P0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQOuZ0ONqClr0xyWQyfdBw9Z2JBLIqFI',
    appId: '1:795859017189:android:5e26bdfcecbef43e53230c',
    messagingSenderId: '795859017189',
    projectId: 'travelapp-428516',
    storageBucket: 'travelapp-428516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5D83O8LTU9MUYP04dxc4eS6hr0qhzeFo',
    appId: '1:795859017189:ios:bf296a496d95ceb453230c',
    messagingSenderId: '795859017189',
    projectId: 'travelapp-428516',
    storageBucket: 'travelapp-428516.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5D83O8LTU9MUYP04dxc4eS6hr0qhzeFo',
    appId: '1:795859017189:ios:bf296a496d95ceb453230c',
    messagingSenderId: '795859017189',
    projectId: 'travelapp-428516',
    storageBucket: 'travelapp-428516.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Qfm0kEEILIuqvgu21OnlhSkWoBiyVNQ',
    appId: '1:795859017189:web:67d84c17bade40a253230c',
    messagingSenderId: '795859017189',
    projectId: 'travelapp-428516',
    authDomain: 'travelapp-428516.firebaseapp.com',
    storageBucket: 'travelapp-428516.appspot.com',
    measurementId: 'G-H4B6DPDZY6',
  );

}